name: References check

on:
  - push
  - pull_request

jobs:
  reference_diff:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install puppet-strings
      run: |
        sudo apt update
        sudo apt install -y ruby
        sudo gem install puppet puppet-strings
    - name: Generate temporary strings
      run: |
        puppet strings generate --format markdown --out /tmp/references.md -d
    - name: Compare the actual and expected
      run: |
        if ! cmp "REFERENCE.md" "/tmp/references.md"; then
          diff -u REFERENCE.md /tmp/references.md
          echo "Diff between expected references and the commited file, please regenerate references \
          with puppet strings generate --format markdown --out REFERENCE.md and commit them"
          exit 1
        else
          echo "References are up to date"
        fi
